services:
  profile-ms: 
    container_name: profile-ms
    build: 
      context: ./profile-microservice
      dockerfile: Dockerfile-dev
    volumes:
      - ./profile-microservice:/usr/src/app
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - PROFILE_DB_USER=${PROFILE_DB_USER}
      - PROFILE_DB_PASSWORD=${PROFILE_DB_PASSWORD}
      - PROFILE_DB_HOST=${PROFILE_DB_HOST}
  reviews-ms:
    container_name: reviews-ms
    build: 
      context: ./reviews-microservice
      dockerfile: Dockerfile-dev
    volumes:
      - ./reviews-microservice:/usr/src/app
    environment:
      - PROFILE_DB_USER=${PROFILE_DB_USER}
      - PROFILE_DB_PASSWORD=${PROFILE_DB_PASSWORD}
      - PROFILE_DB_HOST=${PROFILE_DB_HOST}
  music-ms:
    container_name: music-ms
    build:
      context: ./music-ms
      dockerfile: Dockerfile
    restart: unless-stopped
    # Puerto comentado para que solo sea accesible a través del API Gateway
    # ports:
    #   - "3002:3002"
    environment:
      # - PORT=3002
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_NAME=music_ms
      - MONGODB_TIMEOUT=10
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27018:27017"  # Exponer en un puerto distinto para evitar conflictos
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null  # Reducir logs
  aleph-frontend:
    container_name: aleph-frontend
    build: 
      context: ./aleph-frontend
      dockerfile: Dockerfile.dev
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - music-ms
  apigateway:
    container_name: apigateway
    build: 
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  auth-ms:
    container_name: auth-ms
    build:
      context: ./auth-ms
      dockerfile: Dockerfile
    volumes:
      - ./auth-ms:/app
      - /app/node_modules
    environment:
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=alephmusicmanagement@gmail.com
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=Aleph <alephmusicmanagement@gmail.com>
      - FRONTEND_URL=http://localhost:3000
      - MONGO_URI=${MONGO_URI}
    ports:
      - "4000:4000"
  aleph-frontend-dsk:
    build:
      context: ./aleph-frontend-dsk
      dockerfile: Dockerfile
    container_name: aleph-frontend-dsk
    restart: unless-stopped
    
    # Configuración para GUI (X11 forwarding)
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - ELECTRON_DISABLE_SECURITY_WARNINGS=1
      - NODE_ENV=production
    
    # Volúmenes para X11 y persistencia de datos
    volumes:
      # Socket X11 para mostrar GUI en host Linux
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Directorio home del usuario para persistir datos
      - electron-home:/home/electronuser
      # Opcional: mapear directorio de descargas
      - ./downloads:/home/electronuser/Downloads
      # Opcional: mapear configuración de la app
      - ./app-data:/home/electronuser/.config
    
    # Configuración de red
    network_mode: host
    
    # Privilegios necesarios para GUI
    privileged: false
    security_opt:
      - seccomp:unconfined
    
    # Dispositivos necesarios para audio/video
    devices:
      - /dev/dri:/dev/dri  # GPU access
      
volumes:
  electron-home:
    driver: local
  profile_data:
  reviews_data:
  mongo-data: