services:
  profile-ms: 
    container_name: profile-ms
    build: 
      context: ./profile-microservice
      dockerfile: Dockerfile-dev
    volumes:
      - ./profile-microservice:/usr/src/app
    environment:
      - S3_ACCESS_KEY=secret
      - S3_SECRET_KEY=secret
      - PROFILE_DB_USER=${PROFILE_DB_USER}
      - PROFILE_DB_PASSWORD=${PROFILE_DB_PASSWORD}
      - PROFILE_DB_HOST=${PROFILE_DB_HOST}
  reviews-ms:
    container_name: reviews-ms
    build: 
      context: ./reviews-microservice
      dockerfile: Dockerfile-dev
    volumes:
      - ./reviews-microservice:/usr/src/app
    environment:
      - PROFILE_DB_USER=${PROFILE_DB_USER}
      - PROFILE_DB_PASSWORD=${PROFILE_DB_PASSWORD}
      - PROFILE_DB_HOST=${PROFILE_DB_HOST}
  music-ms:
    container_name: music-ms
    build:
      context: ./music-ms
      dockerfile: Dockerfile
    restart: unless-stopped
    # Puerto comentado para que solo sea accesible a través del API Gateway
    # ports:
    #   - "3002:3002"
    environment:
      # - PORT=3002
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_NAME=music_ms
      - MONGODB_TIMEOUT=10
      - SPOTIFY_CLIENT_ID=secret
      - SPOTIFY_CLIENT_SECRET=secret
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27018:27017"  # Exponer en un puerto distinto para evitar conflictos
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null  # Reducir logs
  aleph-frontend:
    container_name: aleph-frontend
    build: 
      context: ./aleph-frontend
      dockerfile: Dockerfile.dev
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=secret
      - GOOGLE_CLIENT_ID=secret
      - GOOGLE_CLIENT_SECRET=secret
    ports:
      - "3000:3000"
    depends_on:
      - music-ms
  apigateway:
    container_name: apigateway
    build: 
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  auth-ms:
    container_name: auth-ms
    build:
      context: ./auth-ms
      dockerfile: Dockerfile
    volumes:
      - ./auth-ms:/app
    environment:
      - PORT=4000
      - JWT_SECRET=secret
      - EMAIL_USER=alephmusicmanagement@gmail.com
      - EMAIL_PASS=secret
      - EMAIL_FROM=Aleph <alephmusicmanagement@gmail.com>
      - FRONTEND_URL=http://localhost:3000
      - MONGO_URI=secret
    ports:
      - "4000:4000"
      
volumes:
  profile_data:
  reviews_data:
  mongo-data: