services:
  profile-ms:
    container_name: profile-ms
    build: 
      context: ./profile-microservice
      dockerfile: Dockerfile-dev
    volumes:
      - ./profile-microservice:/usr/src/app
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - AZURE_DB_USER=${AZURE_DB_USER}
      - AZURE_DB_PASSWORD=${AZURE_DB_PASSWORD}
      - AZURE_DB_HOST=${AZURE_DB_HOST}
    networks:
      # private_net: 
      #   ipv4_address: 172.20.1.3
      private_net: 
        ipv4_address: 172.20.1.9
      ms_net:
        ipv4_address: 172.20.2.4
  reviews-ms:
    container_name: reviews-ms
    build: 
      context: ./reviews-microservice
      dockerfile: Dockerfile-dev
    volumes:
      - ./reviews-microservice:/usr/src/app
    environment:
      - AZURE_DB_USER=${AZURE_DB_USER}
      - AZURE_DB_PASSWORD=${AZURE_DB_PASSWORD}
      - AZURE_DB_HOST=${AZURE_DB_HOST}
    networks:
      # private_net: 
      #   ipv4_address: 172.20.1.4
      private_net:
        ipv4_address: 172.20.1.10
      ms_net:
        ipv4_address: 172.20.2.5
  music-ms:
    container_name: music-ms
    build:
      context: ./music-ms
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_NAME=${MONGODB_NAME}
      - MONGODB_TIMEOUT=10
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    networks:
      # private_net:
      #   ipv4_address: 172.20.1.6
      private_net:
        ipv4_address: 172.20.1.13
      ms_net:
        ipv4_address: 172.20.2.7
  music-ms-a:
    container_name: music-ms-a
    build:
      context: ./music-ms
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      private_net:
        ipv4_address: 172.20.1.14
      ms_net:
        ipv4_address: 172.20.2.8
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_NAME=${MONGODB_NAME}
      - MONGODB_TIMEOUT=10
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
  music-ms-b:
    container_name: music-ms-b
    build:
      context: ./music-ms
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      private_net:
        ipv4_address: 172.20.1.15
      ms_net:
        ipv4_address: 172.20.2.9
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_NAME=${MONGODB_NAME}
      - MONGODB_TIMEOUT=10
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
  music-load-balancer:
    image: nginx:latest
    container_name: music-load-balancer
    networks:
      private_net:
        ipv4_address: 172.20.1.12
    # ports: 
    #   - "8082:80"
    volumes:
      - ./music-load-balancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - music-ms
      - music-ms-a
      - music-ms-b
  streaming-ms:
    container_name: streaming-ms
    build:
      context: ./streaming-ms
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      # public_net:
      #   ipv4_address: 172.20.0.5
      private_net:
        ipv4_address: 172.20.1.4
      # app_net:
      #   ipv4_address: 172.20.2.15
    # ports:
    #   - "8081:8080"  # Exponer WebSocket para conexión directa desde el frontend
    environment:
      - PORT=8080
      - API_GATEWAY_URL=http://apigateway:8080
      - S3_ACCESS_KEY=${MUSIC_S3_ACCESS_KEY}
      - S3_SECRET_KEY=${MUSIC_S3_SECRET_KEY}
      - S3_BUCKET_NAME=${MUSIC_S3_BUCKET_NAME}
      - AWS_REGION=${MUSIC_AWS_REGION}
    depends_on:
      - apigateway
      - music-ms
  aleph-frontend:
    container_name: aleph-frontend
    build: 
      context: ./aleph-frontend
      dockerfile: Dockerfile.dev
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - APIGATEWAY_INT_URL=${APIGATEWAY_INT_URL}
      - NODE_TLS_REJECT_UNAUTHORIZED=0  # Acepta certificados self-signed para desarrollo
    extra_hosts:
      - "localhost:host-gateway"  # Permite resolver localhost desde el contenedor
    networks:
      public_net:
        ipv4_address: 172.20.0.3
      private_net:
        ipv4_address: 172.20.1.3
    # ports:
    #   - "3000:3000"
    depends_on:
      - music-ms
      - streaming-ms   

  apigateway:
    container_name: apigateway
    build: 
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks:
      private_net: 
        ipv4_address: 172.20.1.5
      # app_net:
      #   ipv4_address: 172.20.2.2

    # ports:
    #   - "8080:8080"
  aleph_message_queue:
    image: bitnami/kafka:latest
    container_name: aleph_message_queue
    networks:
      # private_net:
      #   ipv4_address: 172.20.1.9
      private_net:
        ipv4_address: 172.20.1.6
    # ports:
    #   - "9092:9092"  
    #   - "9093:9093"  
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://aleph_message_queue:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@aleph_message_queue:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
  aleph_kafka_consumer:
    container_name: aleph_kafka_consumer
    build: 
      context: ./kafka-consumer
      dockerfile: Dockerfile
    depends_on:
      - aleph_message_queue
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=aleph_message_queue:9092
      - TOPIC_SONG_PLAYED_NAME=song-played-topic
      - AZURE_DB_USER=${AZURE_DB_USER}
      - AZURE_DB_PASSWORD=${AZURE_DB_PASSWORD}
      - AZURE_DB_HOST=${AZURE_DB_HOST}
      - ANALYSIS_DB_NAME=${ANALYSIS_DB_NAME}
    networks:
      # private_net:
      #   ipv4_address: 172.20.1.10
      private_net:
        ipv4_address: 172.20.1.7
      ms_net:
        ipv4_address: 172.20.2.2
  analysis-ms:
    container_name: analysis-ms
    build:
      context: ./analysis-ms
      dockerfile: Dockerfile
    networks:
      # private_net:
      #   ipv4_address: 172.20.1.8
      private_net:
        ipv4_address: 172.20.1.8
      ms_net:
        ipv4_address: 172.20.2.3
    # ports:
    #   - "8001:8000"  
    environment:
      - DB_HOST=${AZURE_DB_HOST}
      - DB_PORT=5432
      - DB_NAME=${ANALYSIS_DB_NAME}
      - DB_USER=${AZURE_DB_USER}
      - DB_PASSWORD=${AZURE_DB_PASSWORD}
  auth-ms:
    container_name: auth-ms
    build:
      context: ./auth-ms
      dockerfile: Dockerfile
    volumes:
      - ./auth-ms:/app
      - /app/node_modules
    environment:
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=alephmusicmanagement@gmail.com
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=Aleph <alephmusicmanagement@gmail.com>
      - FRONTEND_URL=https://localhost
      - AUTH_MONGO_URI=${AUTH_MONGO_URI}
    networks:
      # private_net:
      #   ipv4_address: 172.20.1.5
      private_net:
        ipv4_address: 172.20.1.11
      ms_net:
        ipv4_address: 172.20.2.6
    # ports:
    #   - "4000:4000"
  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    networks:
      public_net:
        ipv4_address: 172.20.0.2
      private_net:
        ipv4_address: 172.20.1.2
    ports:
      - "443:443"
    depends_on:
      - apigateway
      - aleph-frontend

networks:
  public_net:
    driver: bridge
    internal: false
    ipam: 
      config:
        - subnet: 172.20.0.0/26
          gateway: 172.20.0.1
  
  private_net: 
    driver: bridge
    internal: true
    ipam:
      config: 
        - subnet: 172.20.1.0/26
          gateway: 172.20.1.1
  
  ms_net:
    driver: bridge
    internal: false
    ipam:
      config: 
        - subnet: 172.20.2.0/26
          gateway: 172.20.2.1



