events {}


http {
    upstream music_service {
        least_conn;
        server music-ms:3002;
        server music-ms-a:3002;
        server music-ms-b:3002;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://music_service;
        }
    }
}