events {}

http {
    upstream music_service {
        server music-ms:3000;
        server music-ms-a:3000;
        server music-ms-b:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://music_service;
        }
    }
}