events {}

http {
    upstream profile_service {
        least_conn;
        server profile-ms:3000;
        server profile-ms-a:3000;
        server profile-ms-b:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://profile_service;
        }
    }
}