// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Album struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	ReleaseDate *string   `json:"release_date,omitempty"`
	SpotifyID   *string   `json:"spotify_id,omitempty"`
	ImageURL    *string   `json:"image_url,omitempty"`
	Year        *int      `json:"year,omitempty"`
	CreatedAt   *string   `json:"created_at,omitempty"`
	UpdatedAt   *string   `json:"updated_at,omitempty"`
	ArtistIds   []string  `json:"artist_ids,omitempty"`
	Songs       []*Song   `json:"songs,omitempty"`
	Artists     []*Artist `json:"artists,omitempty"`
}

type Artist struct {
	ID         string   `json:"id"`
	Name       string   `json:"name"`
	SpotifyID  *string  `json:"spotify_id,omitempty"`
	ImageURL   *string  `json:"image_url,omitempty"`
	Genres     []string `json:"genres,omitempty"`
	Popularity *int     `json:"popularity,omitempty"`
	CreatedAt  *string  `json:"created_at,omitempty"`
	UpdatedAt  *string  `json:"updated_at,omitempty"`
	Albums     []*Album `json:"albums,omitempty"`
	Songs      []*Song  `json:"songs,omitempty"`
}

type Category struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Slug     *string  `json:"slug,omitempty"`
	ImageURL *string  `json:"image_url,omitempty"`
	Genres   []*Genre `json:"genres,omitempty"`
}

type Genre struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Slug  string `json:"slug"`
	Count *int   `json:"count,omitempty"`
}

type Query struct {
}

type Song struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Duration    int       `json:"duration"`
	SpotifyID   *string   `json:"spotify_id,omitempty"`
	AlbumID     *string   `json:"album_id,omitempty"`
	TrackNumber *int      `json:"track_number,omitempty"`
	AudioURL    *string   `json:"audio_url,omitempty"`
	CreatedAt   *string   `json:"created_at,omitempty"`
	UpdatedAt   *string   `json:"updated_at,omitempty"`
	Album       *Album    `json:"album,omitempty"`
	Artists     []*Artist `json:"artists,omitempty"`
}
