events {}
worker_processes auto;

http {
    log_format detailed '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status $body_bytes_sent '
                       '"$http_referer" "$http_user_agent" '
                       'upstream: $upstream_addr '
                       'upstream_status: $upstream_status '
                       'upstream_response_time: $upstream_response_time';
    
    access_log /var/log/nginx/access.log detailed;
    error_log /var/log/nginx/error.log debug;

    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # limit_req_zone $binary_remote_addr zone=limitador_api:10m rate=20r/s;
    limit_req_zone $binary_remote_addr zone=limitador_frontend:10m rate=100r/s;
    limit_req_zone $binary_remote_addr zone=limitador_ws:10m rate=50r/s;


    # upstream apigateway {
    #     server 172.20.1.24:80;
    # }

    server {
        listen 443 ssl;
        server_name aleph;
        keepalive_timeout   70;

        ssl_certificate /etc/ssl/certs/aleph-cert.pem;
        ssl_certificate_key /etc/ssl/private/aleph-key.pem;

        # location /api/v1/ {
        #     #  limit_req zone=limitador_api burst=10 nodelay;
        #     #  limit_req_status 429;
        #     proxy_pass http://apigateway-load-balancer; 
        #     # proxy_pass http://apigateway;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #     proxy_set_header X-Forwarded-Proto $scheme;
        #  }



        location / {
            limit_req zone=limitador_frontend burst=10 nodelay;
            limit_req_status 429;

            proxy_pass http://aleph-frontend:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

        }

        location /ws {
            proxy_pass http://streaming-ms:8080/ws;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwarded-Host $server_name;
            proxy_cache_bypass $http_upgrade;
            
        }
    }
}
