events {}

http {
    upstream apigateway_service {
        least_conn;
        server apigateway:8080;
        server apigateway-a:8080;
        server apigateway-b:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://apigateway_service;
        }
    }
}